// OpenCode plugin generator.
// Produces a global plugin for ~/.config/opencode/plugins/.

import { homedir } from "node:os";
import { join } from "node:path";

const RECEIVER = join(homedir(), ".llm-memory", "bin", "hook-receiver");

export interface OpenCodeHookConfig {
  pluginPath: string;
  content: string;
}

export function buildOpenCodeHookConfig(): OpenCodeHookConfig {
  return {
    pluginPath: "plugins/llm-memory.js",
    content: buildOpenCodePlugin(),
  };
}

export function buildOpenCodePlugin(): string {
  return `// Auto-generated by llm-memory. Do not edit.
import { spawnSync } from "node:child_process";

const receiver = ${JSON.stringify(RECEIVER)};

function object(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}

function sendToolEvent(input, output) {
  const sessionId = process.env.LLM_MEMORY_SESSION_ID;
  if (!sessionId) return;

  const out = object(output);
  const payload = {
    tool: input?.tool,
    args: object(out.args ?? input?.args),
    result: object(out.result ?? out),
    cwd: process.cwd(),
  };

  spawnSync(receiver, ["--event", "PostToolUse", "--session", sessionId], {
    input: JSON.stringify(payload),
    encoding: "utf8",
    stdio: ["pipe", "ignore", "ignore"],
    timeout: 450,
  });
}

export const LLMMemoryPlugin = async () => ({
  "tool.execute.after": async (input, output) => {
    sendToolEvent(input, output);
  },
});
`;
}
